//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IlacinGelsinV2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Yorum
    {
        public int yorumId { get; set; }
        public string yorumIcerik { get; set; }
        public int uyeId { get; set; }
        public int ilacId { get; set; }
        public Nullable<System.DateTime> Tarih { get; set; }
    
        public virtual Ilac Ilac { get; set; }
        public virtual Uye Uye { get; set; }
    }
}
